_meta:
  type: "rolesmapping"
  config_version: 2
kibana_user:
  reserved: true
  hidden: false
  backend_roles:
  - "67a92b1f-aced-4f20-8317-65b23cd7cf85"
  - "76705200-9e93-4975-9e7d-01b8eafcc0be"
  hosts: []
  users: []
  and_backend_roles: []
  description: "Grants basic permissions to use OpenSearch"
cf_user:
  reserved: true
  hidden: false
  backend_roles:
  - "67a92b1f-aced-4f20-8317-65b23cd7cf85"
  - "76705200-9e93-4975-9e7d-01b8eafcc0be"
  hosts: []
  users: []
  and_backend_roles: []
  description: "CF users with privileges to their own spaces"
kibana_server:
  reserved: true
  users:
  - "kibanaserver"
all_access:
  reserved: true
  hidden: false
  backend_roles:
  - "admin"
  hosts: []
  users: []
  and_backend_roles: []
  description: "Administrators with unrestricted access"

