_meta:
  type: "rolesmapping"
  config_version: 2
kibana_user:
  reserved: true
  hidden: false
  backend_roles:
  - "user"
  hosts: []
  users: []
  and_backend_roles: []
  description: "CF users with privileges to their own spaces"
cf_user:
  reserved: true
  hidden: false
  backend_roles:
  - "user"
  hosts: []
  users: []
  and_backend_roles: []
  description: "CF users with privileges to their own spaces"
kibana_server:
  reserved: true
  users:
  - "kibanaserver"
all_access:
  reserved: true
  hidden: false
  backend_roles:
  - "admin"
  hosts: []
  users: []
  and_backend_roles: []
  description: "Administrators with unrestricted access"

