_meta:
  type: "rolesmapping"
  config_version: 2
opensearch_dashboards_user:
  reserved: true
  hidden: false
  backend_roles:
  - "user"
  hosts: []
  users: []
  and_backend_roles: []
  description: "Grants basic permissions to use OpenSearch"
cf_user:
  reserved: true
  hidden: false
  backend_roles:
  - "user"
  hosts: []
  users: []
  and_backend_roles: []
  description: "CF users with privileges to their own spaces"
opensearch_dashboards_server:
  reserved: true
  users:
  - "opensearch_dashboardsserver"
all_access:
  reserved: true
  hidden: false
  backend_roles:
  - "admin"
  hosts: []
  users: []
  and_backend_roles: []
  description: "Administrators with unrestricted access"

